# Generated by Django 3.2.4 on 2021-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210609_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
