version: "3.9"
services:
  db:
    image: "postgres:alpine"
    volumes:
      - ./_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
