# Generated by Django 3.2.4 on 2021-06-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=128)),
                ('publication_data', models.DateField(auto_now=True)),
            ],
        ),
    ]
