# Generated by Django 3.2.4 on 2021-06-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
