# Generated by Django 3.2.4 on 2021-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_publication_data_product_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
    ]
