# Generated by Django 3.2.4 on 2021-06-22 10:09

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=product.models.generate_product_image_file_path),
        ),
    ]
